### ISSUE TITLE
Is there a way to seed the core-periphery assignment for reproducibility?

### ISSUE THREAD

**Issue by syedarehaq** [ryanjgallagher/core_periphery_sbm#1]
When I use the hubspoke.infer() function I get slightly different core-periphery labels on my network, every-time I run it. Is there a way to use seeding so that I can get a reproducible core-periphery assignment every time I run it on top of the same network?

**Comment by ryanjgallagher** [comment]
I don't think I have anything in the code right now that lets you set the seed for the random number generator. I think I should be able to add something like that though. I'll try to do so later next or the following week.

**Comment by syedarehaq** [comment]
It is nothing urgent, but having that feature would be really helpful. Thanks for looking into it.

**Comment by ryanjgallagher** [comment]
Thanks for your patience @syedarehaq. You should be able to use the `seed` parameter with either model now to set the random seed. Just let me know if you run into any issues with it!

Unrelated, but I also added a helper function `get_coreness()`, which returns a continuous coreness value based on the inference. May be helpful for your dissertation work. I've added an example of it to the README, let me know if you have any questions about it

**Comment by syedarehaq** [comment]
Thanks a lot Ryan, this is really helpful!
