### ISSUE TITLE
[Bug] Uninitialized variable in `core_periphery.initialize_inference`

### ISSUE THREAD

**Issue by sztal** [ryanjgallagher/core_periphery_sbm#2]
Hi,

First of all, thanks for developing this package!

I think there is a bug in line 249 in `core_periphery.initialize_inference`. More concretely, the `N` variable in the line below is undefined (this is even confirmed by static code checkers like PyLint, so I think it is indeed a bug):

```python
self.n_mcmc = N * len(self.n_blocks)
```

**Comment by ryanjgallagher** [comment]
Thanks for catching this! Should be fixed now
